### ISSUE TITLE
Would my game become part of the GPL license if I use this addon?

### ISSUE THREAD

**Issue by Joe23232** [sdfgeoff/blender_bevy_toolkit#12]
If I use your addon, would it become part of the gpl license?

**Comment by sdfgeoff** [comment]
No. The Rust code (the part that gets compiled into in your game) is MIT.
Your models (both blend and scn files) are output of blender, and so can be licensed however you like.

The only thing that is GPL'd is the python code, and thats because it includes `import bpy` and hence is a derivative work of blender itself. As a result, if you were to extend the python part of the exporter, that would fall under GPL, but other than that: use as you like!
