### ISSUE TITLE
Exports appear sideways

### ISSUE THREAD

**Issue by piedoom** [sdfgeoff/blender_bevy_toolkit#13]
Hey there - because Bevy is a Y-up world, the export is 90 deg off. I was wondering if there was an option to choose Y as up in the export, or if the solution is to modify the game to just treat Z as up.

**Comment by sdfgeoff** [comment]
In the blender-godot-exporter I worked on a while back, the coordinate system conversion was a constant source of pain, particularly as we got into things like animations. Solvable, but every so often you'd foot-gun yourself with it by applying it twice or thinking it would be applied elsewhere. 
Since I was doing this exporter for my own project and the coordinate system handedness was the same, I decided just to rotate my game to treat Z as up.

I'll leave this issue open for people to convince me that I should change to Y up, but at the moment I am not so inclined to do so.
